version: 2
jobs:
    build:
        docker:
            - image: circleci/openjdk:8-jdk

        working_directory: ~/repo

        environment:
            # Customize the JVM maximum heap limit
            JVM_OPTS: -Xmx3200m
            TERM: dumb
    steps:

        - checkout

        - restore_cache:
              key: spring-data-utils-{{ checksum "pom.xml" }}

        - run: mvn dependency:go-offline

        - save_cache:
              paths:
                  - ~/.m2
              key: spring-data-utils-{{ checksum "pom.xml" }}

        - run: mvn package

        - store_test_results:
              path: target/surefire-reports

        - store_artifacts:
              path: target/spring-data-utils-1.0-SNAPSHOT.jar
