version: 2
jobs:
    build:
        working_directory: ~/spring-data-utils
        docker:
            - image: circleci/openjdk:8-jdk
        steps:
            - checkout
            - restore_cache:
                  key: spring-data-utils-{{ checksum "pom.xml" }}
            - run: mvn dependency:go-offline

            - save_cache:
                  paths:
                      - ~/.m2
                  key: spring-data-utils-{{ checksum "pom.xml" }}

            - run: mvn package

            - store_artifacts:
                  path: target/spring-data-utils-1.0-SNAPSHOT.jar
